version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-java-rest-fromogrinalgithub"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mqp5aw9fmwft"
s3_prefix = "aws-sam-java-rest-fromogrinalgithub"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
